import type { Metadata } from 'next'
import '@/app/css/globals.css'

export const metadata: Metadata = {
  title: 'SniperThink - AI-Driven Automation for Teams',
  description: "Generated by Next.js",
  icons: {
    icon: "/favicon.svg", // path to public/favicon.svg
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
