'use client'

import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface TermsOfUseModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function TermsOfUseModal({ isOpen, onClose }: TermsOfUseModalProps) {
  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div 
          className="fixed inset-0 z-50 flex items-center justify-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.3 }}
        >
          {/* Backdrop */}
          <motion.div 
            className="absolute inset-0 bg-black bg-opacity-50 backdrop-blur-sm"
            onClick={onClose}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
          />
          
          {/* Modal */}
          <motion.div 
            className="relative w-full max-w-4xl max-h-[90vh] mx-4 bg-black border border-gray-700 rounded-lg overflow-hidden"
            initial={{ 
              opacity: 0, 
              scale: 0.9, 
              y: 20 
            }}
            animate={{ 
              opacity: 1, 
              scale: 1, 
              y: 0 
            }}
            exit={{ 
              opacity: 0, 
              scale: 0.9, 
              y: 20 
            }}
            transition={{ 
              duration: 0.3,
              ease: "easeOut"
            }}
          >
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-gray-700">
              <h2 className="text-2xl font-bold text-white">Terms of Use</h2>
              <motion.button
                onClick={onClose}
                className="text-gray-400 hover:text-white transition-colors p-2"
                aria-label="Close modal"
                whileHover={{ scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
              >
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </motion.button>
            </div>

            {/* Content */}
            <motion.div 
              className="overflow-y-auto max-h-[calc(90vh-120px)] p-6"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: 0.1 }}
            >
              <div className="prose prose-lg max-w-none prose-invert">
                <p className="mb-6 text-white">
                  These Terms of Use (the "Terms") constitute a legally binding agreement between you ("you," "your," or "User") and Grey Horizon Ventures Private Limited ("Company," "Sniperthink", "we," "us," or "our").
                </p>

                <p className="mb-6 text-white">
                  By accessing or using our website/application (the "Site"/"App"), you agree to be bound by these Terms of Use and our Privacy Policy, which is published on this Site and is incorporated herein by reference. You further agree to comply with all applicable laws and regulations while using this Site.
                </p>

                <p className="mb-6 text-white">
                  Please be aware that the Site is provided on an "as-is" and "as-available" basis. We do not warrant the accuracy or authenticity of any information obtained through your use of the Site.
                </p>

                <p className="mb-6 text-white">
                  These Terms of Use constitute an electronic record in accordance with the provisions of the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. This agreement is governed by the laws of India.
                </p>

                <p className="mb-6 text-white">
                  You acknowledge and agree that these Terms may be updated from time to time, and such changes will be effective immediately upon posting. We encourage you to review these Terms periodically to stay informed of any updates.
                </p>

                <div className="bg-yellow-900/20 border-l-4 border-yellow-400 p-4 mb-8">
                  <p className="font-bold text-yellow-200">
                    BY ACCESSING OR USING THIS WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF USE. IF YOU DO NOT AGREE TO THESE TERMS, YOU ARE NOT AUTHORIZED TO ACCESS OR USE THE WEBSITE.
                  </p>
                </div>

                {/* Section 1 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">1. SCOPE AND APPLICABILITY</h2>
                <p className="mb-6 text-white">
                  These Terms, together with our Privacy Policy, constitute the entire and sole agreement between you and the Company regarding your access to and use of this Site. For any questions about your use of the Site, please contact us at: hello@sniperthink.com.
                </p>

                <p className="mb-4 text-white">You are permitted to use the Site if you meet the following criteria:</p>
                <ul className="list-disc pl-6 mb-6 text-white">
                  <li className="mb-2">You are 18 years of age or older.</li>
                  <li className="mb-2">You agree to comply with these Terms of Use and our Privacy Policy.</li>
                </ul>

                <p className="mb-6 text-white">
                  The services offered to users may include, but are not limited to: [Insert a brief description of the services offered].
                </p>

                <div className="bg-red-900/20 border-l-4 border-red-400 p-4 mb-8">
                  <p className="font-bold text-red-200">
                    WE RESERVE THE RIGHT TO MODIFY OR DISCONTINUE THE SERVICES OFFERED ON THE SITE AT ANY TIME AT OUR SOLE DISCRETION. ANY SUCH CHANGES WILL BE UPDATED AND REFLECTED IN THESE TERMS. YOU AGREE TO REVIEW THESE TERMS PERIODICALLY FOR UPDATES, AND WE SHALL NOT BE LIABLE TO YOU FOR ANY SUCH MODIFICATIONS OR DISCONTINUANCE.
                  </p>
                </div>

                {/* Section 2 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">2. LICENSE TO USE THE SITE</h2>
                <p className="mb-6 text-white">
                  Subject to your compliance with these Terms, the Company grants you a worldwide, non-exclusive, non-transferable, non-sublicensable, revocable, limited license to access and use the information and services provided on the Site for your internal use. We may terminate this license at any time, for any reason, at our sole discretion.
                </p>

                <p className="mb-6 text-white">
                  You agree that any breach of these Terms will constitute sufficient grounds for the automatic termination of your license to use the Site without prior notice. Upon termination, you must immediately destroy all copies of any materials you have downloaded from the Site. Failure to do so may be considered a copyright infringement, and we reserve the right to pursue any available legal remedies.
                </p>

                <p className="mb-6 text-white">
                  You acknowledge that you are granted only a limited license to use the Site and that you do not acquire any intellectual property rights in or to the Site.
                </p>

                {/* Section 3 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">3. PROHIBITED USES</h2>
                <p className="mb-4 text-white">By accessing and using this Site, you agree that you will not:</p>
                <ol className="list-decimal pl-6 mb-6 space-y-2 text-white">
                  <li>Use the Site if you are under the age of 18.</li>
                  <li>Use any content on the Site in a way that violates any applicable law, rule, or regulation (whether national, international, or local), whether intentionally or unintentionally.</li>
                  <li>Use the Site in any manner that could adversely affect, impair, disable, infect, or overburden our servers, computer systems, networks, or any other components used to provide the Site.</li>
                  <li>Interfere with any third party's use and enjoyment of the Site.</li>
                  <li>Modify or alter any content available on the Site.</li>
                  <li>Copy, reverse engineer, decompile, or commercially or otherwise reuse (including selling, renting, leasing, or distributing) any content you may have accessed or downloaded from the Site, except as expressly permitted.</li>
                  <li>Use any trademarks, logos, or graphics displayed on the Site without our express written consent for any purpose whatsoever.</li>
                  <li>Use the Site's network or any email addresses obtained from the Site for any advertising, promotional, or marketing campaigns without our prior written consent.</li>
                  <li>Upload any content that infringes upon any third party's intellectual property rights or is obscene, pornographic, blasphemous, libelous, pedophilic, or otherwise illegal or prohibited in any manner.</li>
                </ol>

                <p className="mb-6 text-white">
                  If you are found to be in violation of any of these prohibitions, you agree that the Company may initiate legal proceedings against you, which you acknowledge as a fair and just action.
                </p>

                {/* Section 4 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">4. DATA PROTECTION AND PRIVACY</h2>
                <p className="mb-4 text-white">
                  You acknowledge that you have read and fully understood the terms of our Privacy Policy, which is published and displayed on the Site. By using the Site, you consent to the following as detailed in the Privacy Policy:
                </p>
                <ol className="list-decimal pl-6 mb-6 space-y-2 text-white">
                  <li>The types of data being collected by the Company.</li>
                  <li>The purposes for which the data is being collected.</li>
                  <li>The entities that may process the data.</li>
                </ol>

                {/* Section 5 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">5. INTELLECTUAL PROPERTY</h2>
                <p className="mb-6 text-white">
                  You agree that all services offered, software used, content posted or made available on the Site, and any other associated functionalities are the intellectual property of the Company. You agree to keep all information pertaining to these confidential at all times. You further agree not to modify, resell, reuse, license, distribute, or use our intellectual property in any unauthorized manner. Any use of our intellectual property requires our express written authorization and consent. Violation of this clause will be considered a breach of this agreement, and we reserve the right to pursue any legal remedy we deem appropriate to enforce and protect our rights.
                </p>

                {/* Section 6 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">6. TRADEMARKS</h2>
                <p className="mb-6 text-white">
                  You agree that all trademarks, logos, and service marks displayed on the Site are the property of the Company. Any unauthorized use of these is strictly prohibited and may constitute infringement or passing off. Nothing on the Site should be interpreted as granting any license or right, whether express or implied, written or unwritten, to any individual to use any trademarks belonging to the Company.
                </p>

                {/* Section 7 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">7. COPYRIGHT NOTICE</h2>
                <p className="mb-6 text-white">
                  All content published or displayed on the Site is the copyright of the Company. You agree that any form of copying, distribution, or use of such content for any purpose without our express written permission constitutes copyright infringement.
                </p>

                {/* Section 8 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">8. THIRD-PARTY LINKS</h2>
                <p className="mb-6 text-white">
                  The Site may contain links to third-party websites or services that are not owned or controlled by the Company. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such third-party websites or services. We strongly advise you to read the terms and conditions and privacy policies of any third-party websites or services that you visit.
                </p>

                {/* Section 9 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">9. COOKIES AND SIMILAR TECHNOLOGIES</h2>
                <p className="mb-6 text-white">
                  We may use cookies, web beacons, and other similar technologies to collect information about your browsing activities and preferences on our Site. This helps us to improve your experience, understand how the Site is used, and personalize content. By using our Site, you consent to our use of these technologies in accordance with our Privacy Policy. You can manage your cookie preferences through your browser settings. Please refer to our Privacy Policy for more detailed information on our use of cookies and how you can control them.
                </p>

                {/* Section 10 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">10. DISCLAIMER OF WARRANTIES</h2>
                <div className="bg-red-900/20 border-l-4 border-red-400 p-4 mb-8">
                  <p className="text-red-200">
                    TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE SITE AND ITS CONTENT ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. WE DO NOT WARRANT THAT THE SITE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE MAKE NO WARRANTIES REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE CONTENT AVAILABLE ON THE SITE. ANY RELIANCE YOU PLACE ON SUCH INFORMATION IS STRICTLY AT YOUR OWN RISK.
                  </p>
                </div>

                {/* Section 11 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">11. INDEMNIFICATION</h2>
                <p className="mb-6 text-white">
                  You agree to indemnify, defend, and hold harmless the Company and its affiliates, officers, directors, employees, agents, contractors, professionals, and consultants (the "Indemnified Parties") from and against any and all claims, damages, costs, liabilities, and expenses (including, without limitation, reasonable attorneys' fees) arising out of or in connection with: (a) your breach of any applicable law; (b) your illegal or prohibited use of the Site; (c) your breach of any intellectual property or confidentiality obligations; or (d) your negligence or wilful misconduct.
                </p>

                {/* Section 12 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">12. LIMITATION OF LIABILITY</h2>
                <div className="bg-red-900/20 border-l-4 border-red-400 p-4 mb-8">
                  <p className="text-red-200">
                    TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES) ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF (OR INABILITY TO ACCESS OR USE) THE SITE OR ITS CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SITE SHALL NOT EXCEED THE PRICE THAT YOU HAVE PAID FOR AVAILING THE SERVICE OR INR 1000 WHICHEVER IS LOWER.
                  </p>
                </div>

                {/* Section 13 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">13. SEVERABILITY</h2>
                <p className="mb-6 text-white">
                  If any provision of these Terms is held to be invalid or unenforceable for any reason, such provision shall be deemed to be severed from these Terms, and the remaining provisions shall continue in full force and effect. The invalid or unenforceable provision shall be replaced by a valid and enforceable provision that most closely reflects the original intention.
                </p>

                {/* Section 14 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">14. GOVERNING LAW AND JURISDICTION</h2>
                <p className="mb-6 text-white">
                  All matters, claims, and any other issues that may arise directly or indirectly from or in connection with these Terms shall be governed by and construed in accordance with the laws of <em className="text-gray-300">India</em>, without regard to its conflict of law principles. The courts located in <em className="text-gray-300">Noida, UP</em> shall have the sole and exclusive jurisdiction to hear all matters, claims, or any such issues arising directly or indirectly from or in connection with these Terms of Use.
                </p>

                {/* Section 15 */}
                <h2 className="text-2xl font-bold text-white mt-12 mb-4">15. QUESTIONS AND GRIEVANCES</h2>
                <p className="mb-6 text-white">
                  If you have any questions or grievances regarding these Terms of Use, please contact us at: hello@sniperthink.com.
                </p>

                {/* Footer Note */}
                <div className="bg-gray-800/50 border border-gray-600 p-4 mt-12 rounded">
                  <p className="text-sm text-gray-300">
                    <sup>[a]</sup> Typically, jurisdiction is of the country where the company is incorporated.
                  </p>
                </div>
              </div>
            </motion.div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
} 