"use client"

import React from "react"

export function TermsOfUse() {
  return (
    <div className="text-sm text-gray-300 space-y-4">
      <h2 className="text-lg font-semibold mb-2">TERMS OF USE</h2>
      
      <p>
        These Terms of Use (the "Terms") constitute a legally binding agreement between you ("you," "your," or "User") 
        and Grey Horizon Ventures Private Limited ("Company," "Sniperthink", "we," "us," or "our").
      </p>
      
      <p>
        By accessing or using our website/application (the "Site"/"App"), you agree to be bound by these Terms of Use and our Privacy Policy, 
        which is published on this Site and is incorporated herein by reference. You further agree to comply with all applicable laws and 
        regulations while using this Site.
      </p>
      
      <p>
        Please be aware that the Site is provided on an "as-is" and "as-available" basis. We do not warrant the accuracy or authenticity 
        of any information obtained through your use of the Site.
      </p>
      
      <p>
        These Terms of Use constitute an electronic record in accordance with the provisions of the Information Technology Act, 2000. 
        This electronic record is generated by a computer system and does not require any physical or digital signatures. 
        This agreement is governed by the laws of India.
      </p>
      
      <p>
        You acknowledge and agree that these Terms may be updated from time to time, and such changes will be effective immediately upon posting. 
        We encourage you to review these Terms periodically to stay informed of any updates.
      </p>
      
      <p className="font-semibold">
        BY ACCESSING OR USING THIS WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS OF USE. 
        IF YOU DO NOT AGREE TO THESE TERMS, YOU ARE NOT AUTHORIZED TO ACCESS OR USE THE WEBSITE.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">1. SCOPE AND APPLICABILITY</h3>
      
      <p>
        These Terms, together with our Privacy Policy, constitute the entire and sole agreement between you and the Company regarding 
        your access to and use of this Site. For any questions about your use of the Site, please contact us at: hello@sniperthink.com.
      </p>
      
      <p>You are permitted to use the Site if you meet the following criteria:</p>
      
      <p>A. You are 18 years of age or older.</p>
      
      <p>B. You agree to comply with these Terms of Use and our Privacy Policy.</p>
      
      <p>
        The services offered to users may include, but are not limited to: [Insert a brief description of the services offered].
      </p>
      
      <p className="font-semibold">
        WE RESERVE THE RIGHT TO MODIFY OR DISCONTINUE THE SERVICES OFFERED ON THE SITE AT ANY TIME AT OUR SOLE DISCRETION. 
        ANY SUCH CHANGES WILL BE UPDATED AND REFLECTED IN THESE TERMS. YOU AGREE TO REVIEW THESE TERMS PERIODICALLY FOR UPDATES, 
        AND WE SHALL NOT BE LIABLE TO YOU FOR ANY SUCH MODIFICATIONS OR DISCONTINUANCE.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">2. LICENSE TO USE THE SITE</h3>
      
      <p>
        Subject to your compliance with these Terms, the Company grants you a worldwide, non-exclusive, non-transferable, non-sublicensable, 
        revocable, limited license to access and use the information and services provided on the Site for your internal use. 
        We may terminate this license at any time, for any reason, at our sole discretion.
      </p>
      
      <p>
        You agree that any breach of these Terms will constitute sufficient grounds for the automatic termination of your license to use 
        the Site without prior notice. Upon termination, you must immediately destroy all copies of any materials you have downloaded from 
        the Site. Failure to do so may be considered a copyright infringement, and we reserve the right to pursue any available legal remedies.
      </p>
      
      <p>
        You acknowledge that you are granted only a limited license to use the Site and that you do not acquire any intellectual property 
        rights in or to the Site.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">3. PROHIBITED USES</h3>
      
      <p>By accessing and using this Site, you agree that you will not:</p>
      
      <ol className="list-decimal pl-6 space-y-2">
        <li>Use the Site if you are under the age of 18.</li>
        <li>Use any content on the Site in a way that violates any applicable law, rule, or regulation (whether national, international, or local), whether intentionally or unintentionally.</li>
        <li>Use the Site in any manner that could adversely affect, impair, disable, infect, or overburden our servers, computer systems, networks, or any other components used to provide the Site.</li>
        <li>Interfere with any third party's use and enjoyment of the Site.</li>
        <li>Modify or alter any content available on the Site.</li>
        <li>Copy, reverse engineer, decompile, or commercially or otherwise reuse (including selling, renting, leasing, or distributing) any content you may have accessed or downloaded from the Site, except as expressly permitted.</li>
        <li>Use any trademarks, logos, or graphics displayed on the Site without our express written consent for any purpose whatsoever.</li>
        <li>Use the Site's network or any email addresses obtained from the Site for any advertising, promotional, or marketing campaigns without our prior written consent.</li>
        <li>Upload any content that infringes upon any third party's intellectual property rights or is obscene, pornographic, blasphemous, libelous, pedophilic, or otherwise illegal or prohibited in any manner.</li>
      </ol>
      
      <p>
        If you are found to be in violation of any of these prohibitions, you agree that the Company may initiate legal proceedings against you, 
        which you acknowledge as a fair and just action.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">4. DATA PROTECTION AND PRIVACY</h3>
      
      <p>
        You acknowledge that you have read and fully understood the terms of our Privacy Policy, which is published and displayed on the Site. 
        By using the Site, you consent to the following as detailed in the Privacy Policy:
      </p>
      
      <ol className="list-decimal pl-6 space-y-2">
        <li>The types of data being collected by the Company.</li>
        <li>The purposes for which the data is being collected.</li>
        <li>The entities that may process the data.</li>
      </ol>

      <h3 className="text-md font-semibold mt-6 mb-2">5. INTELLECTUAL PROPERTY</h3>
      
      <p>
        You agree that all services offered, software used, content posted or made available on the Site, and any other associated 
        functionalities are the intellectual property of the Company. You agree to keep all information pertaining to these confidential 
        at all times. You further agree not to modify, resell, reuse, license, distribute, or use our intellectual property in any 
        unauthorized manner. Any use of our intellectual property requires our express written authorization and consent. Violation of 
        this clause will be considered a breach of this agreement, and we reserve the right to pursue any legal remedy we deem appropriate 
        to enforce and protect our rights.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">6. TRADEMARKS</h3>
      
      <p>
        You agree that all trademarks, logos, and service marks displayed on the Site are the property of the Company. Any unauthorized 
        use of these is strictly prohibited and may constitute infringement or passing off. Nothing on the Site should be interpreted as 
        granting any license or right, whether express or implied, written or unwritten, to any individual to use any trademarks belonging 
        to the Company.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">7. COPYRIGHT NOTICE</h3>
      
      <p>
        All content published or displayed on the Site is the copyright of the Company. You agree that any form of copying, distribution, 
        or use of such content for any purpose without our express written permission constitutes copyright infringement.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">8. THIRD-PARTY LINKS</h3>
      
      <p>
        The Site may contain links to third-party websites or services that are not owned or controlled by the Company. We have no control 
        over and assume no responsibility for the content, privacy policies, or practices of any third-party websites or services. You further 
        acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or 
        alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through 
        any such third-party websites or services. We strongly advise you to read the terms and conditions and privacy policies of any 
        third-party websites or services that you visit.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">9. COOKIES AND SIMILAR TECHNOLOGIES</h3>
      
      <p>
        We may use cookies, web beacons, and other similar technologies to collect information about your browsing activities and preferences 
        on our Site. This helps us to improve your experience, understand how the Site is used, and personalize content. By using our Site, 
        you consent to our use of these technologies in accordance with our Privacy Policy. You can manage your cookie preferences through 
        your browser settings. Please refer to our Privacy Policy for more detailed information on our use of cookies and how you can control them.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">10. DISCLAIMER OF WARRANTIES</h3>
      
      <p className="uppercase">
        TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE SITE AND ITS CONTENT ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS 
        WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, 
        FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. 
        WE DO NOT WARRANT THAT THE SITE WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. 
        WE MAKE NO WARRANTIES REGARDING THE ACCURACY, RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE CONTENT AVAILABLE ON THE SITE. 
        ANY RELIANCE YOU PLACE ON SUCH INFORMATION IS STRICTLY AT YOUR OWN RISK.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">11. INDEMNIFICATION</h3>
      
      <p>
        You agree to indemnify, defend, and hold harmless the Company and its affiliates, officers, directors, employees, agents, contractors, 
        professionals, and consultants (the "Indemnified Parties") from and against any and all claims, damages, costs, liabilities, and 
        expenses (including, without limitation, reasonable attorneys' fees) arising out of or in connection with: (a) your breach of any 
        applicable law; (b) your illegal or prohibited use of the Site; (c) your breach of any intellectual property or confidentiality 
        obligations; or (d) your negligence or wilful misconduct.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">12. LIMITATION OF LIABILITY</h3>
      
      <p className="uppercase">
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
        SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, DATA, USE, GOODWILL, OR 
        OTHER INTANGIBLE LOSSES) ARISING OUT OF OR RELATING TO YOUR ACCESS TO OR USE OF (OR INABILITY TO ACCESS OR USE) THE SITE OR ITS 
        CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), STATUTE, OR ANY OTHER LEGAL THEORY, EVEN IF WE HAVE 
        BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING 
        TO THESE TERMS OR THE SITE SHALL NOT EXCEED THE PRICE THAT YOU HAVE PAID FOR AVAILING THE SERVICE OR INR 1000 WHICHEVER IS LOWER.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">13. SEVERABILITY</h3>
      
      <p>
        If any provision of these Terms is held to be invalid or unenforceable for any reason, such provision shall be deemed to be 
        severed from these Terms, and the remaining provisions shall continue in full force and effect. The invalid or unenforceable 
        provision shall be replaced by a valid and enforceable provision that most closely reflects the original intention.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">14. GOVERNING LAW AND JURISDICTION</h3>
      
      <p>
        All matters, claims, and any other issues that may arise directly or indirectly from or in connection with these Terms shall be 
        governed by and construed in accordance with the laws of India, without regard to its conflict of law principles. The courts located 
        in Noida, UP shall have the sole and exclusive jurisdiction to hear all matters, claims, or any such issues arising directly or 
        indirectly from or in connection with these Terms of Use.
      </p>

      <h3 className="text-md font-semibold mt-6 mb-2">15. QUESTIONS AND GRIEVANCES</h3>
      
      <p>
        If you have any questions or grievances regarding these Terms of Use, please contact us at: hello@sniperthink.com.
      </p>
    </div>
  )
}

export default TermsOfUse
